[Server] Documented manifest endpoints with apidoc
raven-os/build-raven-os-org pull request #42
Opened 2019-07-21 21:22 UTC by BourgoisMickael

2019-07-27 17:30 UTC, Arignir requested changes
I'm counting on you to apply the suggested modifications on all routes

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/create.js
> + * @apiDescription Create a manifest to compile
```suggestion
 * @apiDescription Create a new manifest that can be used to compile a package
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/create.js
> + *    "name": "bonjour",
Please avoid french word as example, and use realistic content (like `gcc`, `glibc` whatever)

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/create.js
> + *    "name": "to_compile",
Would be great to be consistent with the example above, so it feels like it is its response.

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/create.js
> + * @apiError  {String}    errors.param   Request parameter in error
```suggestion
 * @apiError  {String}    errors.param   The request parameter that caused the error
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/create.js
> + * @apiError  {string}    errors.detail  Detail about the parameter in error
```suggestion
 * @apiError  {string}    errors.detail  Details about the parameter that caused the error
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/create.js
> + * @apiError  {string}    errors.value   Value of the parameter provided
```suggestion
 * @apiError  {string}    errors.value   Value provided for the invalid parameter
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/get.js
> + * @apiDescription Retrieve a manifest
```suggestion
 * @apiDescription Fetch a manifest's content and metadata
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/create.js
> + * @apiSuccess  {Integer}   id                    Id of the manifest
```suggestion
 * @apiSuccess  {Integer}   id                    ID of the manifest
```

(This mistake is present a couple more time in the PR)

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/get.js
> + * @apiSuccess  {Object[]}  history               List of content (last updated first)
```suggestion
 * @apiSuccess  {Object[]}  history               List of content (ordered by last_update)
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/get.js
> + * @apiSuccess  {String}    history.edition_date  Date of content edition
```suggestion
 * @apiSuccess  {String}    history.edition_date  Date when the manifest was edited
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/get.js
> + * @apiSuccess  {String}    history.content       The content of the manifest
```suggestion
 * @apiSuccess  {String}    history.content       Content of an edition of the manifest 
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/get.js
> + *    "name": "to_compile",
Same here

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/list.js
> + * @apiParam  (Query String) {String}                             [name]              Search results starting by provided name
```suggestion
 * @apiParam  (Query String) {String}                             [name]              Search for manifests with a name starting with `name`
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/list.js
> + * @apiParam  (Query String) {String='creation','update','name'}  [sort='creation']   Sort by provided column
```suggestion
 * @apiParam  (Query String) {String='creation','update','name'}  [sort='creation']   Sort the results by the provided criteria
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/list.js
> + * @apiParam  (Query String) {String='asc','desc'}                [dir='desc']        Direction of the sorting
```suggestion
 * @apiParam  (Query String) {String='asc','desc'}                [dir='desc']        Sort direction
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/list.js
> + * @apiSuccess  {Integer}   meta.pagination.pageCount   Number of pages containing results
```suggestion
 * @apiSuccess  {Integer}   meta.pagination.pageCount   Total number of pages
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/update.js
> + * @apiParam  (Body)   {String{1..}}  content Content of the manifest
```suggestion
 * @apiParam  (Body)   {String{1..}}  content New content of the manifest
```

2019-07-27 17:30 UTC, Arignir commented on server/src/action/manifest/create.js
> + *    "content": "{{content of a python file manifest}}"
```suggestion
 *    "content": "{{content of a build manifest (python)}}"
```

2019-08-01 13:30 UTC, person-m submitted a review, later dismissed

2019-08-05 17:34 UTC, Arignir submitted a review, later dismissed

2019-08-06 18:29 UTC, Arignir approved these changes

2019-08-06 18:30 UTC, merged